# Generated by Django 4.0.1 on 2022-02-06 13:31

import apps.note.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_historicaltopic_historicalsubject_historicalprogram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalchapterset',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalchapterset',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchapterset',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='historicaldescription',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldescription',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsubject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltopic',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicaltopic',
            name='history_user',
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='chapterset',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='description',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default='Empty', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='HistoricalChapter',
        ),
        migrations.DeleteModel(
            name='HistoricalChapterSet',
        ),
        migrations.DeleteModel(
            name='HistoricalDescription',
        ),
        migrations.DeleteModel(
            name='HistoricalProgram',
        ),
        migrations.DeleteModel(
            name='HistoricalSubject',
        ),
        migrations.DeleteModel(
            name='HistoricalTopic',
        ),
    ]
