# Generated by Django 4.0.1 on 2022-02-06 13:32

import apps.note.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0003_remove_historicalchapterset_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='chapterset',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='description',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default='u_9aSzkwAU', on_delete=models.SET(apps.note.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
