# Generated by Django 4.0.1 on 2022-02-06 13:37

import apps.question.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_historicalquestionsetter_historicalquestionpaper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='historicalquestionpaper',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquestionpaper',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalquestionpaper',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='historicalquestionsetter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquestionsetter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='historicalquestionsetter',
            name='question_paper',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='null', on_delete=models.SET(apps.question.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default='null', on_delete=models.SET(apps.question.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='user',
            field=models.ForeignKey(default='null', on_delete=models.SET(apps.question.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='questionsetter',
            name='user',
            field=models.ForeignKey(default='null', on_delete=models.SET(apps.question.models.GET_DELETED_USER), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='HistoricalAnswer',
        ),
        migrations.DeleteModel(
            name='HistoricalQuestion',
        ),
        migrations.DeleteModel(
            name='HistoricalQuestionPaper',
        ),
        migrations.DeleteModel(
            name='HistoricalQuestionSetter',
        ),
    ]
