# Generated by Django 4.0.1 on 2022-02-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, length=8, max_length=40, prefix='u_')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('role', models.IntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin'), (4, 'staff')], verbose_name='Role')),
                ('date_joined', models.DateTimeField(blank=True, editable=False, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
